### ISSUE TITLE
mod: cannot access './StarMade-dedicated-server-linux.sh': No such file or directory

### ISSUE THREAD

**Issue by MrKeon** [japtain-cack/starmade-server#1]
Hello,

I tried running this docker script and received the following error.
### Script:
`#!/bin/bash
sudo docker run -d -it --name=starmade1 \
-v /opt/starmade/world1:/home/starmade/server \
-p 4343:4343/tcp \
-e STARMADE_WORLD=world1 \
-e STARMADE_HOST-NAME-TO-ANNOUNCE-TO-SERVER-LIST=[my public ip]\
-e STARMADE_SERVER-LIST-NAME="blah name server blah" \
-e STARMADE_SERVER-LIST-DESCRIPTION="blah blah blah" \
-e STARMADE_PROTECT-STARTING-SECTOR="true" \
-e STARMADE_SUPER-ADMIN-PASSWORD-USE="true" \
-e STARMADE_SUPER-ADMIN-PASSWORD="secret" \
-e STARMADE_MINING-BONUS=5 \
nsnow/starmade-server:latest
`

### Error:
`chmod: cannot access './StarMade-dedicated-server-linux.sh': No such file or directory`

**Comment by japtain-cack** [comment]
Sorry for missing this. This project has moved to gitlab, and this issues has been addressed.

https://gitlab.com/japtain_cack/starmade-server/.
